"""Publish one training run's weights to the Hugging Face Hub with a model card.

    python train/publish_weights.py jb_20260922-211844_27b robbalian/rev-qwen3.8-27b [--private] [--dry-run]

Fetches checkpoint.pt, metadata.json, manifest.json, status.json and trained_development.json from the run directory
on the Modal volume `jev-decision-training` into a staging directory (`modal volume get`), writes README.md (the model
card, filled from the checkpoint metadata and the holdout result), then creates the repo (exist_ok) and uploads the
folder with huggingface_hub using the HF_TOKEN environment variable. optimizer.pt is never fetched or uploaded.
`--dry-run` does everything except the upload and prints the staged tree and the rendered card. A run whose
checkpoint.pt does not exist yet (still training) is reported and exits with status 2.

Requirements: modal (logged in), huggingface_hub; torch is optional (used to read the metadata inside checkpoint.pt,
which is where a calibration temperature would live; metadata.json is the fallback).
"""
import argparse,hashlib,json,os,shutil,subprocess,sys,tempfile
from pathlib import Path

VOLUME='jev-decision-training'
FILES=['checkpoint.pt','metadata.json','manifest.json','status.json','trained_development.json']
OPTIONAL={'manifest.json','status.json','trained_development.json'}
PUBLIC_DECISIONS=19792;SYNTH_DECISIONS=6285
GITHUB='https://github.com/robbalian/rev'

def fetch(run,filename,dest):
 """`modal volume get` one file; returns True on success, False when the file does not exist on the volume."""
 r=subprocess.run([sys.executable,'-m','modal','volume','get',VOLUME,run+'/'+filename,str(dest),'--force'],capture_output=True,text=True)
 if r.returncode==0 and dest.exists():return True
 if dest.exists():dest.unlink()
 return False

def read_json(path):
 try:return json.loads(Path(path).read_text())
 except Exception:return None

def checkpoint_metadata(path):
 """metadata dict and example count from inside checkpoint.pt (torch), else None."""
 try:
  import torch
  c=torch.load(path,map_location='cpu',weights_only=False)
  return dict(c.get('metadata') or {}),c.get('examples'),len(c.get('adapters') or {})
 except Exception as e:
  print('note: could not read checkpoint.pt with torch (%s); using metadata.json'%type(e).__name__,flush=True);return None

def short_name(model):return model.split('/')[-1]

def model_card(run,repo_id,metadata,examples,adapters,manifest,status,dev,sha256):
 model=metadata.get('model','?');revision=metadata.get('revision','?');temperature=metadata.get('temperature')
 synthetic=run.startswith('jb_')
 train_rows=(manifest or {}).get('train_rows');holdout_rows=(manifest or {}).get('holdout_rows',975)
 data=('%s public decisions plus %s synthetic rule-labelled decisions'%(f'{PUBLIC_DECISIONS:,}',f'{SYNTH_DECISIONS:,}') if synthetic else '%s public decisions'%f'{PUBLIC_DECISIONS:,}')
 if train_rows:data+=' (%s rows after the 4,096-token filter and holdout exclusion' %f'{train_rows:,}'+(', %s used'%f'{examples:,}' if examples else '')+')'
 elif examples:data+=' (%s examples used)'%f'{examples:,}'
 if dev and 'accuracy' in dev:
  acc='**%.1f%%** on the frozen %s-question public holdout (NLL %.3f)'%(dev['accuracy']*100,f'{holdout_rows:,}',dev.get('nll',float('nan')))
  rows=''.join('| %s | %d / %d | %.1f%% |\n'%(s,c,n,100*c/n) for s,(c,n) in (dev.get('by_source') or {}).items())
  by_source=('\n| Source | Correct | Accuracy |\n|---|---|---|\n'+rows) if rows else ''
 else:acc='not recorded for this run (trained_development.json missing)';by_source=''
 elapsed=(status or {}).get('elapsed_seconds');train_time=(' in %.0f minutes on one %s'%(elapsed/60,metadata.get('gpu','GPU'))) if elapsed else ''
 temp_line=('Calibration temperature `%s` (stored in the checkpoint metadata; scores are divided by it before the softmax).'%temperature) if temperature is not None else 'No calibration temperature is stored in this checkpoint (the server uses T = 1).'
 synth_para=('\n\nThe synthetic set (`data/synth_jevbench.jsonl.gz`, generated by `train/synth_jevbench.py` in the repo) covers long policies with lookups, date and quantity arithmetic, multi-hop records, routing, traps, yes/no and ordered-level questions; every label is derived by rule from the generated facts, and a wrong "helpful note" is planted on purpose so the model learns not to copy it.' if synthetic else '')
 return f'''---
license: mit
base_model: {model}
pipeline_tag: text-classification
tags:
- lora
- pointer-head
- decision-model
- qwen3.5
- rev
language:
- en
---

# Rev decision model: {short_name(model)} (`{run}`)

A [Rev]({GITHUB}) decision model: a frozen **{model}** backbone with a rank-16 LoRA on every layer's attention and
DeltaNet projections (`q/k/v/o_proj`, `in_proj_qkv/z/a/b`, `out_proj`; alpha 32) and a 256-d pointer head. Given a
state (a document, JSON record or text), a question and a set of named options, the head scores each option's last
token against the decision token and takes a softmax over the offered options only. **No tokens are generated**: one
forward pass returns a choice and a probability per option, for any number of options.

This is the checkpoint of training run `{run}`.

| | |
|---|---|
| Base model | [`{model}`](https://huggingface.co/{model}) at revision `{revision}` |
| Adapter | rank {metadata.get('rank','16')}, alpha {metadata.get('alpha','32')}, {adapters or '?'} linear modules, {(f"{metadata['trainable_parameters']:,}" if isinstance(metadata.get('trainable_parameters'),int) else '?')} trainable parameters (LoRA + head) |
| Head | two 256-d linear projections (`headq` on the decision token, `headk` on each option's last token), FP32 |
| Training data | {data} |
| Holdout accuracy | {acc} |
| Training | {metadata.get('epochs',1)} epoch{train_time}; {metadata.get('training','')}; adapter lr {metadata.get('adapter_lr','?')}, head lr {metadata.get('head_lr','?')}, states up to {metadata.get('max_tokens','4096')} tokens, paired option orders with KL consistency weight {metadata.get('consistency_weight','?')} |
| Checkpoint sha256 | `{sha256}` |
| License | MIT (the adapter and head weights; the base model keeps its own license) |
{by_source}
{temp_line}

## Training data

Trained on {data}: multiple-choice reading and reasoning decisions from public datasets (SocialIQA, CosmosQA, RACE,
MultiRC, ContractNLI and others), each rendered as state + question + options, filtered to 4,096 tokens, and each seen
in two option orders with a KL consistency term so the answer does not depend on where the right option sits.{synth_para}

**Not trained on:** the frozen evaluation sets in the repo (`eval_sets/`, including the {f'{holdout_rows:,}'}-question
public holdout, excluded by question id and by source document), any JevBench item (public or held back), and Jev's
official 102-question workflow set. The holdout number above is measured on data the model never saw.

## Files

- `checkpoint.pt`: `torch.save` dict with `adapters` (`{{module_path: {{'a': (16, in), 'b': (out, 16)}}}}`, FP32),
  `headq` / `headk` state dicts (`weight: (256, hidden)`), `metadata` (this card's numbers) and `examples`.
  Merge rule: `W += (alpha / rank) * B @ A = 2 * B @ A`.
- `metadata.json`, `manifest.json` (data checksums and pinned base revisions), `status.json`,
  `trained_development.json` (the holdout run: per-question choices and probabilities).

## Serving

The base model is downloaded from the Hub at the pinned revision, the LoRA is merged into its weights, and the heads
are loaded. Everything needed is in [`serve_local.py`]({GITHUB}/blob/main/serve_local.py):

```bash
pip install torch transformers accelerate huggingface_hub fastapi uvicorn
# optional, faster DeltaNet layers on CUDA: pip install flash-linear-attention causal-conv1d
git clone {GITHUB} && cd rev
python serve_local.py --repo {repo_id} --port 8000
```

`--selftest` loads the model, answers one hard-coded request and exits. The Modal deployment with cross-request
batching is `serve/server.py` in the same repo.

## Request / response

`POST /score` takes one state and any number of questions about it; every question is scored in one padded forward.

```bash
curl -s http://127.0.0.1:8000/score -H 'content-type: application/json' -d '{{
  "state": {{"invoice": {{"number": "INV-2041", "vendor": "Northwind Traders", "total_usd": 1240.0, "po_match": true}}}},
  "questions": [
    {{"id": "q1", "instructions": "Is the invoice total greater than $500?",
     "criteria": {{"yes": "The total exceeds $500", "no": "The total is $500 or less"}}}},
    {{"id": "q2", "instructions": "What should happen to this invoice next?",
     "criteria": {{"approve": "Approve for payment", "reject": "Reject and return to vendor", "escalate": "Escalate to a manager"}}}}
  ]
}}'
```

```json
{{"answers": {{"q1": {{"choice": "yes", "probabilities": {{"yes": 0.99, "no": 0.01}}}},
             "q2": {{"choice": "approve", "probabilities": {{"approve": 0.9, "reject": 0.02, "escalate": 0.08}}}}}},
 "server_seconds": 0.05, "path": "rows", "rows": [...], "generated_tokens": 0}}
```

`state` may be any JSON value (serialised compactly) or, since this checkpoint was trained with
`state_format = {metadata.get('state_format','json')}`, a plain string passed through as is. `criteria` maps option key to
description; the keys come back as `choice` and as the `probabilities` keys. `POST /ping` returns the server
metadata and `GET /health` returns `{{"ok": true}}`.

The prompt the model sees is

```
State:
<state>
Question: <instructions>
Options:
<key>: <description>
...
Decision:
```

and the score for an option is `(W_q h_decision) . (W_k h_option) / 16`{' / T' if temperature is not None else ''}, softmaxed over the offered options.

## Source

Code, data, evaluation sets and the full write-up: {GITHUB}. The recipe descends from
[Kev](https://github.com/jaredpalmer/kev) by Jared Palmer.
'''

def main():
 ap=argparse.ArgumentParser(description=__doc__.split('\n\n')[0],formatter_class=argparse.RawDescriptionHelpFormatter,epilog=__doc__.split('\n',1)[1])
 ap.add_argument('run',help='run directory on the volume, e.g. jb_20260922-211844_27b')
 ap.add_argument('repo_id',help='Hugging Face repo id, e.g. robbalian/rev-qwen3.8-27b')
 ap.add_argument('--private',action='store_true',help='create the repo as private')
 ap.add_argument('--dry-run',action='store_true',help='fetch, write the card and print the tree; do not upload')
 ap.add_argument('--out',default=None,help='staging directory (default: a temp dir, removed after a successful upload)')
 a=ap.parse_args()
 out=Path(a.out) if a.out else Path(tempfile.mkdtemp(prefix='rev-publish-'));out.mkdir(parents=True,exist_ok=True)
 print('staging in',out,flush=True)
 present=[]
 for f in FILES:
  ok=fetch(a.run,f,out/f);print(('  fetched ' if ok else '  missing ')+f,flush=True)
  if ok:present.append(f)
  elif f not in OPTIONAL:
   status=read_json(out/'status.json') if (out/'status.json').exists() else None
   if f=='checkpoint.pt' and status is None:fetch(a.run,'status.json',out/'status.json');status=read_json(out/'status.json')
   print('\n%s has no %s on the volume (status: %s). The run is probably still training; retry later.'%(a.run,f,json.dumps(status) if status else 'no status.json'),flush=True);sys.exit(2)
 for stray in ('optimizer.pt',):
  if (out/stray).exists():(out/stray).unlink();print('  removed',stray,flush=True)
 manifest=read_json(out/'manifest.json');status=read_json(out/'status.json');dev=read_json(out/'trained_development.json')
 inside=checkpoint_metadata(out/'checkpoint.pt')
 if inside:metadata,examples,adapters=inside
 else:metadata,examples,adapters=(read_json(out/'metadata.json') or {}),(status or {}).get('training_examples'),None
 if not metadata:sys.exit('no metadata found in checkpoint.pt or metadata.json')
 if status and status.get('status') not in (None,'complete'):print('WARNING: status.json says %r; publishing anyway'%status.get('status'),flush=True)
 sha256=hashlib.sha256((out/'checkpoint.pt').read_bytes()).hexdigest()
 card=model_card(a.run,a.repo_id,metadata,examples,adapters,manifest,status,dev,sha256);(out/'README.md').write_text(card)
 print('\n'+a.repo_id+'/')
 for p in sorted(out.iterdir()):print('  %-32s %12s bytes'%(p.name,f'{p.stat().st_size:,}'))
 if a.dry_run:
  print('\n----- README.md -----\n'+card+'----- end README.md -----\n\ndry run: nothing uploaded. Staged files remain in',out);return
 token=os.environ.get('HF_TOKEN')
 if not token:sys.exit('HF_TOKEN is not set')
 from huggingface_hub import HfApi
 api=HfApi(token=token)
 url=api.create_repo(a.repo_id,repo_type='model',private=a.private,exist_ok=True)
 print('repo',url,flush=True)
 api.upload_folder(folder_path=str(out),repo_id=a.repo_id,repo_type='model',commit_message='Publish %s'%a.run,ignore_patterns=['optimizer.pt','*.tmp'])
 print('uploaded https://huggingface.co/'+a.repo_id,flush=True)
 if not a.out:shutil.rmtree(out,ignore_errors=True)

if __name__=='__main__':main()
